# Generated by Django 3.1.7 on 2021-04-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('lecture', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('numOfStudents', models.IntegerField()),
                ('gpa', models.FloatField()),
                ('ap', models.IntegerField()),
                ('a', models.IntegerField()),
                ('am', models.IntegerField()),
                ('bp', models.IntegerField()),
                ('b', models.IntegerField()),
                ('bm', models.IntegerField()),
                ('cp', models.IntegerField()),
                ('c', models.IntegerField()),
                ('d', models.IntegerField()),
                ('dm', models.IntegerField()),
                ('f', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
