# Generated by Django 3.1.7 on 2021-05-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210430_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeinfo',
            name='term',
        ),
        migrations.AddField(
            model_name='gradeinfo',
            name='semester',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradeinfo',
            name='year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
