name: CI

on:
  pull_request:
    branches: [master, develop]
  
  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install package
        run: yarn install --frozen-lockfile
      
      - name: Run lint
        run: yarn run lint
      
      - name: Build test
        run: yarn run prod-build
  
  server:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./server
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
      
      - name: Install dependencies
        run: pipenv install --dev
      
      - name: Generate .env
        run: cp .env.example .env
      
      - name: Run lint
        run: pipenv run lint
      
      - name: Run test
        run: pipenv run test
