name: CI

on:
  pull_request:
    branches: [master, develop]
  
  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      name: Install package
        run: npm ci
      name: Run lint
        run: npm run lint
      name: Build test
        run: npm run prod-build
  
  # server:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./server
    
  #   steps:
  #     - uses: actions/checkout@v2
